version: "3.3"
services:
  db:
    image: postgres
    restart: always
    environment:
      MYSQL_DATABASE: "yt_permissions"
      MYSQL_USER: "postgres"
      MYSQL_PASSWORD: "docker"
      MYSQL_ROOT_PASSWORD: "docker"
    ports:
      - "5432:5432"